server:
  port: 30300

spring:
  application:
    name: cloud-order-hystrix-payment

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7001/eureka/
