server:
  port: 30001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.22.185:3306/cloud?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 2000528gmy
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: Hikari
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期.
      max-lifetime: 400000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.gmy.entity    # 所有Entity别名类所在包

eureka:
  instance:
    hostname: cloud-payment-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka/