server:
  port: 30001

spring:
  application:
    name: cloud-payment-provider-nacos
  cloud:
    nacos:
      discovery:
        server-addr: http://43.138.22.185:8848  # 配置nacos 地址

management:
  endpoints:
    web:
      exposure:
        include: '*'